apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hde7n6b8q-go 
  janus-idp.io/tekton: hde7n6b8q-go
  backstage.io/kubernetes-id: hde7n6b8q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hde7n6b8q-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml